function myProblem = data_myProblem(projectName)


myProblem.name  = projectName;

%% Problem activity

myProblem.onoff_RTO  = 0;
myProblem.onoff_SCFO = 0;

%% Solver : fsolve
% 'trust-region-dogleg'
% {'levenberg-marquardt',.005}
myProblem.Solver.options = optimset('Algorithm','trust-region-dogleg',...
                                    'LargeScale','on',...
                                    'Diagnostics','off',...
                                    'Display','off' ,...
                                    'FunValCheck','off',...
                                    'MaxFunEvals',10000,...
                                    'MaxIter',10000,...
                                    'TolFun',1e-8,...
                                    'TolX',1e-8);

%% ODE : Time Integration

myProblem.ODE.t_start  = [];
myProblem.ODE.t_final  = [];
myProblem.ODE.t_old    = [];
myProblem.ODE.t_delta  = [];
myProblem.ODE.t_sample = [];
myProblem.ODE.options  = odeset('RelTol'      ,1e-8  , ...
                                'AbsTol'      ,1e-8  , ...
                                'NormControl' ,'on' , ...
                                'OutputFcn'   ,[]    , ...
                                'Stats'       ,'on' , ...
                                'MaxStep'     , 1   , ...
                                'NonNegative' , []);
                            
%% Optimizer : fmincon

myProblem.OPT.options = optimoptions(@fmincon,'Algorithm','sqp', ...
                                              'MaxIter',10000,...
                                              'Display', 'iter',...
                                              'MaxFunEvals',10000,...
                                              'TolFun',1e-8,...
                                              'TolCon',1e-8,...
                                              'TolX',1e-8,...
                                              'FinDiffType','forward',...%'forward' (default), or 'central'
                                              'ScaleProblem','obj-and-constr');
                            
%% Time constants

myProblem.TC.TimeConstantOff = 0;


end

